spring:
  datasource:
    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:tcp://localhost/~/test
    url: jdbc:h2:tcp://localhost:1521/token
    username: song
    password: song1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    root: info
    song.pg.payment: debug
server:
  port: 8081

grpc:
  server:
    port: 50051
